name: openim
packages:
  - .
  - openim_common
  - openim_live
  - openim_meeting
  - openim_organization

command:
  bootstrap:
    runPubGetInParallel: true

scripts:
  pub_upgrade: melos exec -- flutter pub upgrade
  pub_outdated: melos exec -- flutter pub outdated
  pub_get: |
    dart run tool/sync_versions.dart && \
    melos bootstrap && \
    melos exec -- flutter pub get
